#pragma config(Sensor, dgtl1,  touchsensor,    sensorTouch)
#pragma config(Sensor, dgtl2,  loadingled8,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  loadingled7,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  loadingled6,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  loadingled5,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  loadingled4,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  loadingled3,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  loadingled2,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  loadingled1,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, redled,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellowled,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, greenled,       sensorLEDtoVCC)
#pragma config(Motor,  port3,           MOTOR,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           MOTORR,        tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           MOTORRR,       tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           MOTORRRR,      tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           SERVO,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Rename devices when build is done

// Possibly get the robot to make a U-turn (not necessary)

// Look for speaker module and ask if we can use it in our build

task main()
{
	turnLEDOff(redled);
	turnLEDOff(yellowled);
	turnLEDOff(greenled);
	turnLEDOff(loadingled1);
	turnLEDOff(loadingled2);
	turnLEDOff(loadingled3);
	turnLEDOff(loadingled4);
	turnLEDOff(loadingled5);
	turnLEDOff(loadingled6);
	turnLEDOff(loadingled7);
	turnLEDOff(loadingled8);
	setServo(SERVO, 127);
	while(true) {
		turnLEDOff(redled);
		turnLEDOff(yellowled);
		turnLEDOff(greenled);
		turnLEDOff(loadingled1);
		turnLEDOff(loadingled2);
		turnLEDOff(loadingled3);
		turnLEDOff(loadingled4);
		turnLEDOff(loadingled5);
		turnLEDOff(loadingled6);
		turnLEDOff(loadingled7);
		turnLEDOff(loadingled8);
		turnLEDOn(yellowled);
		wait(1);
		turnLEDOff(yellowled);
		turnLEDOn(greenled);
		untilTouch(touchsensor);
		turnLEDOff(greenled);
		turnLEDOn(redled);
		//Decrease soeed so marbles do not fall
		//Make sure gear startup runs sommth with these changes, if so, apply to reverse drive
		//Adjust in the future and delete these lines
		startMotor(MOTOR, 127);
		startMotor(MOTORR, 127);
		startMotor(MOTORRR, 127);
		startMotor(MOTORRRR, 127);
		turnLEDOn(loadingled1);
		wait(1);
		turnLEDOn(loadingled2);
		wait(1);
		turnLEDOn(loadingled3);
		wait(1);
		stopMotor(MOTOR);
		stopMotor(MOTORR);
		stopMotor(MOTORRR);
		stopMotor(MOTORRRR);
		turnLEDOn(loadingled4);
		wait(0.5);
		// Actual Pseudo CODE (not sure if this is right)
		setServo(SERVO, -127);
		wait(0.5);
		setServo(SERVO, 127);
		turnLEDOn(loadingled5);
		wait(1);
		turnLEDOn(yellowled);
		startMotor(MOTOR, -127);
		startMotor(MOTORR, -127);
		startMotor(MOTORRR, -127);
		startMotor(MOTORRRR, -127);
		wait(1);
		turnLEDOn(loadingled6);
		wait(1);
		turnLEDOn(loadingled7);
		untilTouch(touchsensor);
		turnLEDOn(loadingled8);
		turnLEDOn(greenled);
		stopMotor(MOTOR);
		stopMotor(MOTORR);
		stopMotor(MOTORRR);
		stopMotor(MOTORRRR);
		wait(1);
	}
}
